[package]
name = "game_dsl"
version = "0.1.0"
edition = "2021"
authors = ["Eric Olson"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
